### ISSUE TITLE
ArcGIS

### ISSUE THREAD

**Issue by stgruber** [geocryology/HorizonPy#9]
Make function that:
- reads image files derived from ArcGIS SkyMaps
- digitized them by using a contouring function
- derives horizon lines from it
This need no user interaction other than picking a file and displaying the results. As bare bones, it can be a function that accepts an image and spits out a horizon csv.

**Comment by nicholas512** [comment]
Added the arcsky.py file in 4113d4795df142ec6bc7cb207e6a0bf05e519b72 .
